name: bootingRaspi
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: booting
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          #!/bin/sh
          
          echo ...UBSLEEPY deploying...
          cd /home/ruru/UBSLEEPY/
          git reset --hard
          git --git-dir=.git pull origin main
          echo pull ok.
          
          echo ...UBSLEEPY restarting...
          if pgrep -f "main.py" > /dev/null; then
              pkill -f "main.py"
              echo killed.
          else
              echo not killed.
          fi
          RUNNER_TRACKING_ID="" && nohup python3 main.py &
          echo boot ok.
